### ISSUE TITLE
[Epic] Recipe

### ISSUE THREAD

**Issue by Druue** [Druue/rps#1]
Example recipe data
```jsonc
{
    "recipe": {
        "name": "Tiramisu",
        "author": "Druue",
        "blurb": "This is my family tiramisu recipe",
        "ingredients": [
            {
                "name": "Coffee",
                "measurement": {
                    "amount": 40,
                    "unit": "ml"
                }
            },
            {
                "name": "Egg Yolks",
                "measurement": {
                    "amount": 4
                }
            },
            {
                "name": "Amaretto",
                "measurement": {
                    "amount": 10,
                    "unit": "ml"
                }
            }
        ],
        "method": [
            { "1": "Brew coffee" },
            { "2": "Beat egg yolks" }
        ],
        "time": 30000, // in seconds
        "difficulty": "easy",
        "tags": [
            "vegetarian",
            "alcoholic",
            "caffeinated"
        ]
    }
}
```

Primary:
- [ ] Recipe View
- [ ] There should be a way to edit the recipe
    - [ ] Directly by the author
    - [ ] With suggestions from another user
- [ ] There should be a way / option to "swipe" through the instructions, rather than scrolling through it
- [ ] There should be a way to export the recipe

Extended:
- [ ] Comments from users
- [ ] Add to shopping list (maybe this ties back to the suggestions for edits?)
