### ISSUE TITLE
[Epic] Recipes

### ISSUE THREAD

**Issue by Druue** [Druue/rps#2]
- [ ] Recipes View
    - (effectively a card list where each displays an image, title, author, tags, and maybe a short blurb?)
- [ ] User's should be able to click on a recipe to open it
- [ ] There should be a way to upload (a) recipe(s)
- [ ] Recipes should be filterable by
    - [ ] name, ingredient, duration, difficulty, and tags(vegan, GF)
    - [ ] (Extended) what's in the pantry
